language: node_js
branches:
  only:
    master
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
